version: "3.9"
services:
  backend:
    image: springboot-backend
    build:
      context: ./backend
    ports:
      - "8080:8080"

  frontend:
    image: react-frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
